
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-17T17:12:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "51916b88adadaab4e06ff1bc96a661ad2e5f2da5",
 "version": "1.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
