
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-07T09:44:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c6b6bb403b766ff14e3b5ea27d109c31f3acc2cb",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
